[package]
name = "esprit2-client"
version = "0.1.0"
edition = "2021"

[dependencies]
esprit2.path = "../"
esprit2-server.path = "../server"
mlua = "0.9.9"
rand = "0.8.5"
sdl2 = { version = "0.37.0", features = ["image", "ttf", "gfx"] }
serde = "1.0.208"
thiserror = "1.0.63"
toml = "0.8.19"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
rkyv = "0.8.5"
clap = { version = "4.5.16", features = ["derive"] }
